name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - jupyterlab=3.0.12
  - seaborn 
  - pandas
  - pip
  - pandas-profiling
  - pyarrow
  - numpy
  - pip:
      - protobuf==4.23.1
      - wandb==0.10.31
variables:
  PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python