name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - pandas
  - pytest
  - scipy
  - pip
  - numpy
  - pip:
      - protobuf==4.23.1
      - wandb==0.10.31
variables:
  PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python