name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - notebook
  - jupyterlab
  - cookiecutter
  - hydra-core
  - matplotlib
  - pandas
  - git
  - pip
  - numpy
  - pip:
      - protobuf==4.23.1
      - mlflow
      - wandb==0.10.31
